language: php

php:
  - "5.6"
  - "7.0"

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script: phpunit
