language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script: phpunit --bootstrap phpunit_bootstrap.php tests/